tasks:
  # - name: movie_text
  #   exp_group: re_annotation_20
  #   models: [qwen3-30b-fp8]
  #   release_model_after_task: false
  #   objects:
  #     - workload: movie
  #       queries:
  #         # - [Q1]  # Target F1: 0.97
  #         - [Q2]  # Target F1: 1.00
  #   collect:
  #     execution_trace:
  #       iterations: ALL
  #       features: [
  #         pred_eval.f1, trans_eval.f1, L_static,
  #         L_rew, penalty_rew, L_obj,
  #         L_LOO, penalty_LOO, L_subj,
  #         overall_selectivity, total_size,
  #         features,
  #       ]
  - name: ecomm_text
    exp_group: re_annotation_20
    models: [qwen3-30b-fp8]
    release_model_after_task: false
    objects:
      - workload: ecomm
        queries:
          - [Q2]
          - [Q13]
    collect:
      execution_trace:
        iterations: ALL
        features: [
          pred_eval.f1, trans_eval.f1, L_static,
          L_rew, penalty_rew, L_obj,
          L_LOO, penalty_LOO, L_subj,
          overall_selectivity, total_size,
          features,
        ]
  # - name: mmqa_text
  #   exp_group: re_annotation_20
  #   models: [qwen3-30b-fp8]
  #   release_model_after_task: false
  #   objects:
  #     - workload: mmqa
  #       queries:
  #         # - [Q3a]  # Target F1: 0.83
  # - name: medical_text
  #   exp_group: re_annotation_20
  #   models: [qwen3-30b-fp8]
  #   release_model_after_task: false
  #   objects:
  #     - workload: medical
  #       queries:
  #         # - [Q1]  # Target F1: 0.52
