tasks:
  - name: ecomm_text_image
    exp_group: re_annotation_20
    models: [qwen3-30b-fp8, qwen3-vl-30b]
    release_model_after_task: true
    objects:
      - workload: ecomm
        queries:
          - [Q1]
          - [Q2]
          - [Q13] # Target F1: 0.80
    collect:
      execution_trace:
        iterations: ALL
        features: [
          pred_eval.f1, trans_eval.f1, L_static,
          L_rew, penalty_rew, L_obj,
          L_LOO, penalty_LOO, L_subj, 
          overall_selectivity, total_size,
          features,
        ]
