tasks:
  - name: dynamic_data
    exp_group: re_vary_delta
    models: [
            # qwen3-30b-fp8,
            qwen3-vl-30b,
            ]
    release_model_after_task: false
    config_override:
      dynamic_setting: [[
                        #  0.6, 
                        # 0.7, 
                        # 0.8, 
                        # 0.9, 
                         1.0,
                         ]]
    objects:
      - workload: medical
        queries:
          - [
            # Q1,
            # Q3,
            Q8,
            # Q9,
            ]
    collect:
      execution_trace:
        iterations: ALL
        features: [
          pred_eval.f1, trans_eval.f1, L_static,
          L_rew, penalty_rew, L_obj,
          L_LOO, penalty_LOO, L_subj, 
          overall_selectivity, total_size,
          stream_selectivities, stream_sizes,
          features,
        ]